version: '3.2'
services:
  authentication:
    command: node src/server.js
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    # Uncomment lines below for development
    # volumes:
    # - ./auth-service:/app/
    # - /app/node_modules/
    env_file:
      - ./env/auth.env

  movies:
    command: npm run ${MOVIES_MODE:-start}
    build: ./movies-service
    ports:
      - published: ${MOVIES_PORT:-5000}
        target: 3000
    # Uncomment lines below for development
    # volumes:
    #   - ./movies-service:/app/
    #   - /app/node_modules/
    env_file:
      - ./env/movies.env
    depends_on:
      - mongodb
      - authentication

  mongodb:
    image: 'mongo'
    volumes:
      - dbdata:/data/db
    env_file:
      - ./env/mongodb.env

volumes:
  dbdata:
