name: My-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          path: "Netguru"
#     - name: Build docker
#       run: | 
#         echo ---Building and starting up docker---
#         docker-compose -f ./Netguru/docker-compose.yml -d
#         echo ---Containers up---
    - name: Run test
      run: |
        echo --- Running test cases ---
        MOVIES_MODE=test docker-compose -f ./Netguru/docker-compose.yml --build --abort-on-container-exit --exit-code-from movies-service
        echo --- Completed test cases ---
